### ISSUE TITLE
Buildpack support for Symfony apps

### ISSUE THREAD

**Issue by Turbots** [paketo-buildpacks/php#3]
Would it be possible to add a buildpack specifically for Symfony apps?
It would be depending on the composer buildpack if I understand how Symfony works correctly.

**Comment by dmikusa-pivotal** [comment]
It is certainly something that could be done. What specifically would you like it to do?

Right now, it should be possible to run your Symfony apps with the PHP CNBs. The CNBs will run Composer for you, which would include any scripts you have set up to run based off of Composer events, and it should be able to figure out how to start & run your app. If you're seeing problems and that's not working, definitely let us know. Happy to look into it more.

Also, if you're seeing functionality gaps or areas where we could provide more advanced options let us know too. Interested to hear more about potential use cases like this.

**Comment by fg-j** [comment]
Hey @Turbots - checking in about this request. Are you seeing gaps with the current PHP buildpack's support for your Symfony apps? If you're running into problems, please provide an example app that you'd like to be able to build, if you can.

**Comment by fg-j** [comment]
@paketo-buildpacks/php-maintainers Any sense of whether this is still a relevant feature request now that the language family rewrite has been completed?

**Comment by sophiewigmore** [comment]
I think we should close this issue due to lack of activity from OP, and I am not aware of any other requests for this feature (possibly because of the workaround Dan described.)
