### ISSUE TITLE
How to install PDO PHP extension in paketo PHP buildpacks

### ISSUE THREAD

**Issue by tkak** [paketo-buildpacks/php#310]
## What happened?

I'm trying to build CakePHP application using paketo PHP buildpack. But I'm not sure how to install(or enable) PDO PHP extension with PHP bulidpack. It seems that there are no packages related to PDO extension in the package list here.

https://github.com/paketo-buildpacks/stacks/blob/main/packages/full/run

How can I use PDO extension with the PHP buildpack?

* What were you attempting to do?

I'm attempting to build CakePHP application using paketo PHP buildpack.

```
$ pack build cakephp-buildpacks-demo --buildpack gcr.io/paketo-buildpacks/php --builder paketobuildpacks/builder:full --clear-cache
```

* What did you expect to happen?

When I access `http://localhost:8080` with a browser, it shows the CakePHP welcome page.

![image](https://unit.nginx.org/_images/cakephp.png)

* What was the actual behavior? Please provide log output, if possible.

I got the following error page.

```
$ docker run -it --env PORT=8080 -p 8080:8080 cakephp-buildpacks-demo
2021/01/07 03:18:38 [notice] 18#0: using the "epoll" event method
2021/01/07 03:18:38 [notice] 18#0: nginx/1.19.4
2021/01/07 03:18:38 [notice] 18#0: built by gcc 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
2021/01/07 03:18:38 [notice] 18#0: OS: Linux 5.4.39-linuxkit
2021/01/07 03:18:38 [notice] 18#0: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2021/01/07 03:18:38 [notice] 18#0: start worker processes
2021/01/07 03:18:38 [notice] 18#0: start worker process 19
2021/01/07 03:18:38 [notice] 18#0: start worker process 20
[07-Jan-2021 03:18:38] NOTICE: fpm is running, pid 17
[07-Jan-2021 03:18:38] NOTICE: ready to handle connections
172.17.0.1 - - [07/Jan/2021:03:18:44 +0000] "GET / HTTP/1.1" 500 65438 vcap_request_id=-
```
<img width="1280" alt="Screen Shot 2021-01-07 at 12 18 56" src="https://user-images.githubusercontent.com/283992/103846916-86d6ff00-50e2-11eb-9dfa-3114aeffdbbc.png">

## Build Configuration

Please provide some details about your build configuration.

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you using? Please include a version.

```
$ pack --version
0.15.1+git-79adc30.build-1660
```

* What buildpacks are you using? Please include versions.

```
paketo-buildpacks/nginx        0.0.194
paketo-buildpacks/php-dist     0.1.0
paketo-buildpacks/php-composer 0.1.1
paketo-buildpacks/php-web      0.0.136
```

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?

`paketobuildpacks/builder:full`

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

```
$ cat buildpack.yml
---
php:
  webserver: nginx
  webdirectory: webroot

composer:
  install_options: ["--dev"]
```

ref: https://github.com/tkak/cakephp-buildpacks-demo/pull/1

## Checklist

Please confirm the following:

* [x] I have included log output.
* [x] The log output includes an error message.
* [x] I have included steps for reproduction.

**Comment by arjun024** [comment]
Have you tried adding an `.ini` file in `<app-root>/.php.ini.d` with contents similar to follows?:
```
extension=pdo.so
extension=pdo_mysql.so
extension=pdo_odbc.so
...
```

See [PHP CNB docs](https://paketo.io/docs/buildpacks/language-family-buildpacks/php/), the buildpack sets the variable `PHP_INI_SCAN_DIR` to `<APP-ROOT>/.php.ini.d` and thus `.ini` files in this location will be scanned by php.

See an example [app that utilizes this](https://github.com/paketo-buildpacks/php-web/tree/v0.0.100/integration/testdata/php_modules)

**Comment by tkak** [comment]
Thank you for the advice! It worked fine.
