### ISSUE TITLE
Add CA Certificates Buildpack to Group Ordering

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/php#315]
We should add the [CA Certificates Buildpack](https://github.com/paketo-buildpacks/ca-certificates) to each group in the buildpack. This buildpack will allow application developers to provide their own CA certificates and have them included in the root truststore at build and runtime.

**Comment by andymoe** [comment]
I'm going to pick this up.

**Comment by arjun024** [comment]
A note for posterity:

There are 2 paths a user can take while using the php buildpack to create a production server image:
* Using nginx to terminate SSL
* Using httpd to terminate SSL.

Nginx however does not seem to support a configuration where you can tell it use the default/OpenSSL certificate store or a custom directory. The directive to set trusted CAs is `ssl_client_certificate` ([link](ssl_client_certificate)) which only accepts a file - not a directory or an instruction to use the default store. If a user wants to use a custom CA with nginx+php, they can simply mount the file to any arbitrary location and set that as the value of `ssl_client_certificate` - there is no need for the `ca-certificates` buildpack.

ca-certificate buildpack integration is certainly useful for cases when httpd is used (it can use `$SSL_CERT_DIR` which is part of the ca-certificates buildpack contract), or when a php process acts as the client.

**Comment by andymoe** [comment]
@ryanmoran @arjun024 I think this can be closed now (I don't have that power yet)
