### ISSUE TITLE
Add top level [[buildpack.licenses]] field

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/php#335]
## What happened?
We should add the top level `[[buildpack.licenses]]` field to `buildpack.toml` (and all implementation buildpacks) so users can see the buildpack's license through an app image's bill of materials.

**Comment by fg-j** [comment]
@paketo-buildpacks/php-maintainers This has been open for a while. Are there blockers on this work?

**Comment by ryanmoran** [comment]
Yes. There are significant portions of the PHP buildpack that need to be rewritten to allow us to upgrade them to a modern buildpack API version that would be required to support this.

**Comment by sophiewigmore** [comment]
Done, here are some examples:
https://github.com/paketo-buildpacks/php/blob/main/buildpack.toml
https://github.com/paketo-buildpacks/php-dist/blob/main/buildpack.toml
https://github.com/paketo-buildpacks/php-fpm/blob/main/buildpack.toml
https://github.com/paketo-buildpacks/composer/blob/main/buildpack.toml
