### ISSUE TITLE
PHP Restructure

### ISSUE THREAD

**Issue by thitch97** [paketo-buildpacks/php#351]
This issue serves as an outine of the upcoming PHP restructure (per [RFC 001](https://github.com/paketo-buildpacks/php/blob/main/rfcs/0001-restructure.md))

**Steps:**

**Comment by TisVictress** [comment]
@sophiewigmore Feel free to close if this is no longer needed.

**Comment by sophiewigmore** [comment]
Closed out since this issue was opened in April and I'd like to have an accurate timeline of our progress on this, starting with the full issue creation.
