### ISSUE TITLE
Introduce a PHP Start buildpack

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/php#503]
## Context

Part of the implementation of  https://github.com/paketo-buildpacks/php/issues/485 includes the creation of a PHP HTTPD and PHP NGINX buildpacks. These buildpacks are responsible for the following:
- Set up web server configuration
- Set up any additional FPM server-specific configuration
- Set the server start command
- Set the FPM start command

As it stands now, the [PHP Web buildpack ](https://github.com/paketo-buildpacks/php-web) handles all of this logic. The HTTPD/NGINX parts of that buildpack use something called the [`procmgr`](https://github.com/paketo-buildpacks/php-web/tree/main/procmgr) from the buildpack to run multiple start commands (one for server and one for FPM).

It's likely that a similar package to `procmgr` will need to be re-implemented in the new buildpacks to achieve the same double-start command behaviour. 

## Issue
This issue proposes separating the responsibility of setting the start commands for the web servers and FPM into a separate buildpack called PHP Start.

Separating this functionality into its own buildpack will mean that the `procmgr` code will not be duplicated across two buildpacks needlessly. It also will lead to far less complexity in the PHP HTTPD/NGINX buildpacks, which will be responsible just for setting up configuration. This also follows the modular buildpack pattern we see in other language families in Paketo.

## Outcomes
The outcome of this issue should be to come to a consensus as to whether or not we should introduce a PHP Start buildpack to the [PHP Restructure](https://github.com/paketo-buildpacks/rfcs/blob/main/text/php/0001-restructure.md) work, and then depending on the result,  create an addendum RFC to https://github.com/paketo-buildpacks/rfcs/blob/main/text/php/0001-restructure.md to document the decision.

**Comment by dmikusa-pivotal** [comment]
I like this approach.

The following scenarios come up to me:

| What goes in the container | What buildpack sets the start command |
|-----------------------------| ---- | 
| HTTPD + PHPFPM + procmgr | PHP Start |
| Nginx + PHPFPM + procmgr | PHP Start |
| HTTP only but as a proxy to PHPFPM external | PHP HTTPD |
| Nginx only but as a proxy to PHPFPM external | PHP Nginx |
| PHPFPM only | PHP FPM |

I think the existing buildpacks can cleanly handle the last three cases, but it'd be tricky for them to handle the first two. Adding a PHP Start buildpack to handle those cases will keep PHP FPM, PHP HTTPD, and PHP Nginx simpler.

The only downside I see here is that things are getting quite spread out. There are now four buildpacks that can set a start command. You have to have a good understanding of how that works and who's responsible for those scenarios to a.) make future changes confidently and b.) troubleshoot if something unexpected happens.

I definitely think this requires some specific dev docs and possibly a flow chart or something to document how this is expected to behave.

**Comment by sophiewigmore** [comment]
@dmikusa-pivotal I kind of think that the PHP HTTPD and PHP Nginx buildpacks should be fully rid of any and all start commands. In my eyes the PHP Start buildpack should have:
- HTTPD + PHPFPM + procmgr
- HTTPD + PHPFPM + procmgr
- HTTP only but as a proxy to PHPFPM external
- Nginx only but as a proxy to PHPFPM external

I agree that the PHP FPM buildpack should still handle the PHP FPM only case.

**Comment by sophiewigmore** [comment]
RFC has been merged so closing this out!
