### ISSUE TITLE
Pecl extensions?

### ISSUE THREAD

**Issue by enumag** [paketo-buildpacks/php#525]
I'd like to enable some PHP extensions. Some are distributed with core php (such as intl) but others are only available to install using pecl (for instance grpc).

I was unable to find any configuration related to extensions. Is this supported? If not is it planned?

**Comment by sophiewigmore** [comment]
@thitch97 do you have context on this?

**Comment by sophiewigmore** [comment]
@enumag this might be helpful: https://github.com/paketo-buildpacks/php/issues/355#issuecomment-814936498

**Comment by enumag** [comment]
Ah thanks. I think I'll close this issue since it's a duplicate.
