### ISSUE TITLE
Support Jammy Jellyfish

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/php#558]
## Describe the Enhancement

Ultimately, we want to be able to build PHP apps on top of the Paketo Jammy stacks. Currently, builds fail because buildpacks like `php-dist` don't have the Jammy stack listed in their supported stacks. Since the PHP buildpack only works on the Bionic Full stack, we only expect it to be compatible with the Jammy Full stack.

## Possible Solution

- Update `buildpack.toml` and dependencies to add `io.buildpacks.stacks.jammy` as a compatible stack
- (If necessary) Recompile installed dependencies to work on Jammy 
- Add some integration tests that test the buildpack against Jammy

## Motivation

Part of https://github.com/paketo-buildpacks/builder-jammy-full/issues/1

**Comment by joshuatcasey** [comment]
At least the following list needs to be updated:

- [ ] https://github.com/paketo-buildpacks/bundle-install
- [ ] https://github.com/paketo-buildpacks/bundler
- [ ] https://github.com/paketo-buildpacks/mri
- [ ] https://github.com/paketo-buildpacks/passenger
- [ ] https://github.com/paketo-buildpacks/puma
- [ ] https://github.com/paketo-buildpacks/rackup
- [ ] https://github.com/paketo-buildpacks/rails-assets
- [ ] https://github.com/paketo-buildpacks/rake
- [ ] https://github.com/paketo-buildpacks/thin
- [ ] https://github.com/paketo-buildpacks/unicorn

**Comment by fg-j** [comment]
Some investigation into how to compile PHP for Ubuntu 22.04 reveals that PHP 7.* appears not to be compatible with OpenSSL 3, the default OpenSSL installation for Ubuntu 22.04. See [this user thread](https://bugs.php.net/bug.php?id=81540&edit=1) where maintainers indicate that upgrading to PHP 8 is required for compatibility with OpenSSL 3.

As a result, I think it's reasonable to say that Paketo won't support PHP 7 on Jammy. @paketo-buildpacks/php-maintainers, thoughts on this?

**Comment by ryanmoran** [comment]
Here's some more details to support the above: https://www.php.net/manual/en/openssl.requirements.php

> Only PHP >= 8.1 supports OpenSSL >= 3.0
