### ISSUE TITLE
Watchexec missing to enable BP_LIVE_RELOAD_ENABLED=true

### ISSUE THREAD

**Issue by mhoshi-vm** [paketo-buildpacks/php#786]
## Describe the Enhancement

To enable BP_LIVE_RELOAD_ENABLED on php buildpacks

https://github.com/paketo-buildpacks/php-start/blob/main/integration/httpd_reload_test.go#L98

It requires watchexec to be in default, which is not included at the moment.

https://github.com/paketo-buildpacks/php-start/blob/main/integration/httpd_reload_test.go#L133

## Possible Solution

N/A

## Motivation

Want to allow live reload for PHP

**Comment by sophiewigmore** [comment]
@mhoshi-vm thanks for the issue - you're totally right I have no idea how we missed adding the buildpack to the PHP language family buildpack. I'll open a PR for that.
